version: '3.2'

services:
  shortener:
    image: docker.dev.eon.com/dp/shortener:0.22
    networks:
      - gateway
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - 'node.role==worker'
      labels:
        - "traefik.port=9000"
        - "traefik.frontend.rule=PathPrefixStrip:/short"
        - "traefik.docker.network=gateway"
networks:
  gateway:
    external: true